### ISSUE TITLE
Может ли катушка RC522 заменить L1 and C1?

### ISSUE THREAD

**Issue by zoro8** [svk4286/KeyToolsSTM_RC522#1]
Проект RC522 плюс катушки был отличным, простым, дешевым и практичным. Один успех! -Спасибо! 
Я думаю, что могу ли я использовать дополнительную катушку после выключения антенны RC522 с помощью PcdAntennaOff ()? 

Вы можете обновить исходный код?

Еще раз спасибо! !

**Comment by svk4286** [comment]
Нет, антенна RC522 имеет совсем другие параметры, чем самодельная ( L1C1 ) и они не могут заменить друг друга.

**Comment by zoro8** [comment]
> Нет, антенна RC522 имеет совсем другие параметры, чем самодельная ( L1C1 ) и они не могут заменить друг друга.

Я заменил L1C1 катушкой RC522 (без питания), и эксперимент прошел успешно.

**Comment by svk4286** [comment]
Нарисуйте схему подключения.

**Comment by zoro8** [comment]
![RC522](https://user-images.githubusercontent.com/25875561/106351037-8530dd80-6314-11eb-8492-c7f4f873b1ff.png)

**Comment by svk4286** [comment]
Я попробую, но быстро не обещаю..

**Comment by svk4286** [comment]
Такая схема может работать только при отключенном GND от платы RC522. Если GND подключить, то схема работать не будет. И я  не вижу смысла в подобном подключении - с отдельной антенной гораздо удобнее.

**Comment by zoro8** [comment]
> Такая схема может работать только при отключенном GND от платы RC522. Если GND подключить, то схема работать не будет. И я не вижу смысла в подобном подключении - с отдельной антенной гораздо удобнее.

Да я не обратил внимание на проблему заземления.

Из-за плохого согласования катушки LC я хочу использовать антенну RC522.

Конец, спасибо!
