### ISSUE TITLE
Запрос на добавление функций

### ISSUE THREAD

**Issue by zoro8** [svk4286/KeyToolsSTM_RC522#2]
Запрос на увеличение использования флэш-памяти 0x08010000 для сохранения данных Mifare,  для моделирования.
![add](https://user-images.githubusercontent.com/25875561/107146911-f6f8cf00-6985-11eb-99fe-966aabb3c4c4.png)

**Comment by svk4286** [comment]
Не понял вас.

**Comment by zoro8** [comment]
использование stm32 Flash (0x08010000) для сохранения данных Mifare dump. 
Выберите симуляцию в приложении keytools.

**Comment by svk4286** [comment]
Не вижу в этом смысла, можно оперативно загружать любой дамп из смартфона.

**Comment by zoro8** [comment]
> Не вижу в этом смысла, можно оперативно загружать любой дамп из смартфона.

Следующим шагом может автономное симуляцию.

**Comment by svk4286** [comment]
Мне это не надо.

**Comment by zoro8** [comment]
Что ж, спасибо тебе!
